### ISSUE TITLE
History, it's important y0

### ISSUE THREAD

**Issue by hellais** [ilf/twitter-eraser#4]
There should be a feature that before erasing tweets makes a backup copy on your local filesystem and optionally uploads it to some secure location encrypted with a key that only you know.

**Comment by ilf** [comment]
This is a valid use, but I view this as out-of-scope of an _eraser_ tool. The README sais: "Especially since I have my own archive via mail and client logs." Keeping it Unix, I propose to let the eraser erase and create or find another tool to save and backup?

If not, feel free to fork and implement the feature. It should be trivial.

**Comment by hellais** [comment]
@ilf seems like a reasonable argument. I agree. :+1: for not using a non-free license (I am not trolling)!
